<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>7c946e17-c55d-45a8-92af-4dd6f858f4c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ul/li[3]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dcd-btn.dcd-btn-outline-primary.mr-3.my-sm-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb970235-fbc7-47bc-8b9d-ed395ca1761e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.dicoding.com/login</value>
      <webElementGuid>68b69fc9-07bf-4d4a-aba6-ab17e1b6f509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcd-btn dcd-btn-outline-primary mr-3 my-sm-0</value>
      <webElementGuid>86cc6ea4-d952-4118-a043-675e36558204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>e16294cb-4539-4f3a-a570-4b4045bf306f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#login-modal</value>
      <webElementGuid>1aaa2cdc-473c-4296-bc0a-fc8a898c0037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>5381ad88-bfd1-4f86-9ab0-7ff98da6c9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;navbar-menu-wrapper d-flex align-items-stretch w-100&quot;]/ul[@class=&quot;navbar-nav navbar-nav-right&quot;]/li[@class=&quot;nav-item nav-mobile dropdown d-lg-none show&quot;]/div[@class=&quot;dropdown-menu navbar-dropdown mobile-nav show&quot;]/div[@class=&quot;mobile-nav__auth&quot;]/a[@class=&quot;dcd-btn dcd-btn-outline-primary mr-3 my-sm-0&quot;]</value>
      <webElementGuid>911ce596-bb0d-41d5-8473-3eb82aa543c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li[3]/div/div[2]/a</value>
      <webElementGuid>ae918b68-af11-4934-82f4-ade2dc4c43bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Masuk')])[2]</value>
      <webElementGuid>65011ed7-4d4f-48b2-bc6b-43114a18c470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua kelas'])[2]/following::a[1]</value>
      <webElementGuid>9ff96624-1eb0-4768-82f2-f37b31899612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::a[3]</value>
      <webElementGuid>a15dbbb4-08dc-47a4-b0d4-1cda028bfe63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/preceding::a[1]</value>
      <webElementGuid>9613a224-2a5d-4aec-a890-0a6fc6bbe9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning Path'])[2]/preceding::a[2]</value>
      <webElementGuid>5a53f47c-5892-4598-ac70-4529df7ddb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.dicoding.com/login')])[2]</value>
      <webElementGuid>93e011fe-81d5-4659-a1b3-ec6a207f5275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>ea4e2cc1-0cd1-427b-aa8c-3f00c4ed8f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.dicoding.com/login' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>e213f038-b190-4131-a21f-0fb7cf3a275e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
