<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Menjadi Android Developer Expert</name>
   <tag></tag>
   <elementGuidId>958dc4a8-9975-4a9a-ad6d-7a2a5ed26eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//turbo-frame[@id='course-list']/div/div/a/div/div[2]/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.course-card__name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>55931c5e-1a35-4687-bde5-16d821faa418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>course-card__name</value>
      <webElementGuid>5012eb7b-69f2-4144-b4c1-d73179b81667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menjadi Android Developer Expert</value>
      <webElementGuid>68f7cbe0-5c5b-450e-9f7d-acd110e76eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;course-list&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 mb-3&quot;]/a[@class=&quot;course-card course-card--with-logo&quot;]/div[@class=&quot;course-card__leading&quot;]/div[@class=&quot;course-card__content&quot;]/div[@class=&quot;pt-md-2&quot;]/h5[@class=&quot;course-card__name&quot;]</value>
      <webElementGuid>30075fe0-db4d-4bef-aa29-ee83df627037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//turbo-frame[@id='course-list']/div/div/a/div/div[2]/div/h5</value>
      <webElementGuid>5e00cdcf-b713-4ece-88ca-6f6bca7de2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Kelas'])[3]/following::h5[1]</value>
      <webElementGuid>d7836a52-56ce-472f-bba6-0ead4750180a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Kelas'])[1]/following::h5[1]</value>
      <webElementGuid>cb63f158-59f4-4346-b4f8-51f31f0251f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profesional'])[2]/preceding::h5[1]</value>
      <webElementGuid>4d60e3f3-0028-424b-9a43-a9f5db3c2bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belajar Fundamental Aplikasi Android'])[1]/preceding::h5[1]</value>
      <webElementGuid>516d5ca6-27f8-4836-ae0b-f747b72c88de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menjadi Android Developer Expert']/parent::*</value>
      <webElementGuid>b2205115-cd4c-45b6-bbbc-a0af200b2d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>16c29246-52d8-4732-a281-97b4ba40e41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Menjadi Android Developer Expert' or . = 'Menjadi Android Developer Expert')]</value>
      <webElementGuid>89c5a517-2f0f-417a-b7ec-2dc67922cba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
