<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daftar_dcd-hamburger-icon</name>
   <tag></tag>
   <elementGuidId>7bd8fa26-9945-4ee2-bce0-addc7c18b887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mobileNavigation']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dcd-hamburger-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ad1c57b-afd2-4fa5-8551-257bae866d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcd-hamburger-icon</value>
      <webElementGuid>13c06b9b-68db-40d0-bdbf-46056fe16a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileNavigation&quot;)/span[@class=&quot;dcd-hamburger-icon&quot;]</value>
      <webElementGuid>0f27d3b2-85dd-45b2-95b7-e980a591d9a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='mobileNavigation']/span</value>
      <webElementGuid>889d1c60-c172-4e81-abae-761390692ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>af9a383f-a70a-4142-b0ba-6deed9d2cccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
